# Generated by Django 5.1.4 on 2025-01-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_path', models.CharField(max_length=100)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('selected_theme', models.CharField(choices=[('default', 'Light Mode'), ('eclipse', 'Eclipse'), ('material', 'Material'), ('cobalt', 'Cobalt'), ('monokai', 'Monokai'), ('dracula', 'Dracula')], default='default', max_length=20)),
                ('selected_syntax', models.CharField(choices=[('auto', 'Auto Detect'), ('plain', 'Plain Text'), ('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('php', 'PHP'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('go', 'Go'), ('rust', 'Rust'), ('typescript', 'TypeScript')], default='auto', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
