# Generated by Django 5.1.5 on 2025-01-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_repository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='selected_syntax',
        ),
        migrations.RemoveField(
            model_name='project',
            name='selected_theme',
        ),
    ]
