# Generated by Django 5.0.2 on 2024-02-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_path', models.CharField(default='/home/user/dev/codeblock_projects/django-ide-app/source/UserProjects', max_length=100)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('selected_theme', models.CharField(choices=[('default', 'Light Mode'), ('eclipse', 'Eclipse'), ('material', 'Material'), ('cobalt', 'Cobalt'), ('monokai', 'Monokai'), ('dracula', 'Dracula')], default='default', max_length=20)),
                ('selected_syntax', models.CharField(choices=[('auto', 'Auto Detect'), ('plain', 'Plain Text'), ('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('php', 'PHP'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('go', 'Go'), ('rust', 'Rust'), ('typescript', 'TypeScript')], default='auto', max_length=20)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('help', models.TextField(default=" \nRequirements/n\nDjango\nCodeMirror API\nBootstrap API\nInstallation\nClone this repository.\nInstall the required dependencies using pip:\npip install -r requirements.txt\nUsage\nEnsure your Django project is set up.\nAdd 'ide' to the INSTALLED_APPS list in your Django project settings.\nInclude the URLs from the IDE app in your project's urls.py.\nRun migrations to create necessary database tables:\npython manage.py makemigrations\npython manage.py migrate\nBuild the Docker Image:\nsudo docker build -t terminal_session .\nYou can remove the docker image as follows:\ndocker rmi -f terminal_session\nAdd User to Docker Group and set permissions:\nsudo usermod -aG docker your_username\nsudo chmod 666 /var/run/docker.sock\nStart your Django development server:\npython manage.py runserver\nNavigate to the IDE app's URL in your browser to access the IDE. http:127.0.0.1:8000\nFunctionality\nProject Management: Create, edit, rename, and organize files and folders within the project tree.\nDownload Project: Download the entire project for offline access or sharing with others.\nAuto Syntax Highlighting: Automatically highlight syntax for various programming languages for improved readability.\nMultiple Themes: Choose from a variety of themes to personalize your coding environment.\n")),
                ('git', models.TextField(default='\nSome text to explain how to use git...\n')),
            ],
        ),
    ]
