# Generated by Django 5.0.2 on 2024-02-12 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('selected_theme', models.CharField(choices=[('default', 'Light Mode'), ('eclipse', 'Eclipse'), ('material', 'Material'), ('cobalt', 'Cobalt'), ('monokai', 'Monokai'), ('dracula', 'Dracula')], default='default', max_length=20)),
                ('selected_syntax', models.CharField(choices=[('auto', 'Auto Detect'), ('plain', 'Plain Text'), ('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('php', 'PHP'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('go', 'Go'), ('rust', 'Rust'), ('typescript', 'TypeScript')], default='auto', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ide.project')),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_name', models.CharField(max_length=255)),
                ('parent_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdirectories', to='ide.directory')),
                ('files', models.ManyToManyField(to='ide.file')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='ide.project')),
            ],
        ),
    ]
