# Generated by Django 5.0.2 on 2024-12-24 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_path', models.CharField(default='/home/user/dev/codeblock-projects/django-ide-app/source/UserProjects', max_length=100)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('selected_theme', models.CharField(choices=[('default', 'Light Mode'), ('eclipse', 'Eclipse'), ('material', 'Material'), ('cobalt', 'Cobalt'), ('monokai', 'Monokai'), ('dracula', 'Dracula')], default='default', max_length=20)),
                ('selected_syntax', models.CharField(choices=[('auto', 'Auto Detect'), ('plain', 'Plain Text'), ('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('php', 'PHP'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('go', 'Go'), ('rust', 'Rust'), ('typescript', 'TypeScript')], default='auto', max_length=20)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
