# Generated by Django 5.0.2 on 2024-02-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='project_path',
            field=models.CharField(default='C:\\Users\\DanielMarsh\\dev\\django-ide-app\\source\\project', max_length=100),
        ),
        migrations.DeleteModel(
            name='Directory',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
