# Generated by Django 5.0.2 on 2025-01-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0002_project_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
