# Generated by Django 5.1.4 on 2025-01-15 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_title', models.CharField(blank=True, max_length=100, null=True)),
                ('page_title', models.CharField(blank=True, max_length=100, null=True)),
                ('page_heading', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
            },
        ),
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(upload_to='')),
                ('home_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
                ('home_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='ImageOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.ImageField(upload_to='')),
                ('home_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('home_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.homepage')),
            ],
        ),
    ]
