# Generated by Django 5.1.4 on 2025-01-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='send_from_email',
            field=models.EmailField(blank=True, help_text="This email address will be used as the 'from' address when sending automated emails (e.g., password reset).", max_length=254, null=True),
        ),
    ]
