# Generated by Django 5.1.4 on 2025-01-16 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_send_from_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='send_from_email',
        ),
    ]
