# Generated by Django 5.1.5 on 2025-01-21 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_homepage_send_from_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_image', models.ImageField(upload_to='')),
                ('home_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.homepage')),
            ],
        ),
    ]
