# Generated by Django 5.1.5 on 2025-01-21 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_errorimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='page_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='page_title',
        ),
        migrations.CreateModel(
            name='ImageFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_four', models.ImageField(upload_to='')),
                ('home_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='ImageThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_three', models.ImageField(upload_to='')),
                ('home_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='ImageTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_two', models.ImageField(upload_to='')),
                ('home_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.homepage')),
            ],
        ),
    ]
