# Generated by Django 5.1.4 on 2025-01-10 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='drag_drop_message',
        ),
        migrations.CreateModel(
            name='ImageOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.ImageField(upload_to='')),
                ('home_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='landing_page.homepage')),
            ],
        ),
    ]
