# Generated by Django 5.1.4 on 2025-01-15 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='default_cpu_shares',
            field=models.PositiveIntegerField(default=512, help_text='Relative CPU weight for Docker containers.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='default_cpus',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Number of CPUs allocated for Docker containers.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='default_mem_limit',
            field=models.CharField(default='512m', help_text='Default memory limit for Docker containers.', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='default_memswap_limit',
            field=models.CharField(default='1g', help_text='Memory + swap limit for Docker containers.', max_length=10),
        ),
        migrations.AlterField(
            model_name='dockersession',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'running'), ('STOPPED', 'stopped'), ('REMOVED', 'removed')], default='stopped', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_follower', 'New Follower'), ('new_task', 'New Task Assigned'), ('new_message', 'New Message')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
