# Generated by Django 5.0.2 on 2024-12-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activity_log',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
