# Generated by Django 5.1.4 on 2025-01-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_notification_project_notification_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(help_text='The email address used as the sender for password reset and other emails.', max_length=255, verbose_name='Sender Email Address')),
            ],
        ),
    ]
