# Generated by Django 5.1.5 on 2025-01-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_senderemailsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_enabled',
            field=models.BooleanField(default=True, help_text='Indicates whether this notification is enabled.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
