# Generated by Django 5.1.5 on 2025-01-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_activitylog_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='activity_log',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('new_follower', 'New Follower'), ('new_message', 'New Message'), ('task', 'Task'), ('project', 'Project')], max_length=20),
        ),
    ]
