# Generated by Django 5.1.5 on 2025-01-26 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_customuser_activity_log_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDESettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_theme', models.CharField(choices=[('default', 'Dracula (Default)'), ('monokai', 'Monokai'), ('ayu-dark', 'Ayu Dark'), ('light-mode', 'Light Mode'), ('eclipse', 'Eclipse'), ('solarized-light', 'Solarized Light')], default='default', max_length=20)),
                ('selected_syntax', models.CharField(choices=[('auto', 'Auto Detect'), ('plain', 'Plain Text'), ('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('php', 'PHP'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('go', 'Go'), ('rust', 'Rust'), ('typescript', 'TypeScript')], default='auto', max_length=20)),
                ('font_size', models.PositiveIntegerField(default=14)),
                ('show_line_numbers', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
