# Generated by Django 5.1.5 on 2025-01-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_idesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idesettings',
            name='font_size',
        ),
        migrations.AlterField(
            model_name='idesettings',
            name='selected_theme',
            field=models.CharField(choices=[('dracula', 'Dracula (Default)'), ('monokai', 'Monokai'), ('ayu-dark', 'Ayu Dark'), ('light-mode', 'Light Mode'), ('eclipse', 'Eclipse'), ('solarized-light', 'Solarized Light')], default='dracula', max_length=20),
        ),
    ]
