# Generated by Django 5.1.5 on 2025-01-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_idesettings_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idesettings',
            name='auto_close_brackets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='idesettings',
            name='match_brackets',
            field=models.BooleanField(default=True),
        ),
    ]
