# Generated by Django 5.1.5 on 2025-01-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_idesettings_auto_close_brackets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idesettings',
            name='cursor_style',
            field=models.CharField(choices=[('block', 'Block'), ('underline', 'Underline')], default='block', max_length=20),
        ),
        migrations.AddField(
            model_name='idesettings',
            name='font_size',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='idesettings',
            name='highlight_current_line',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='idesettings',
            name='indent_with_tabs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='idesettings',
            name='line_wrapping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idesettings',
            name='minimap',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='idesettings',
            name='tab_size',
            field=models.IntegerField(default=4),
        ),
    ]
