# Generated by Django 5.1.5 on 2025-01-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_idesettings_cursor_style_idesettings_font_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idesettings',
            name='cursor_style',
        ),
        migrations.RemoveField(
            model_name='idesettings',
            name='minimap',
        ),
    ]
