# Generated by Django 5.1.5 on 2025-01-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_idesettings_cursor_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idesettings',
            name='line_wrapping',
            field=models.BooleanField(default=True),
        ),
    ]
