# Generated by Django 5.1.5 on 2025-01-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_idesettings_line_wrapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='idesettings',
            name='linting',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='idesettings',
            name='selected_theme',
            field=models.CharField(choices=[('dracula', 'Dracula'), ('monokai', 'Monokai'), ('ayu-dark', 'Ayu Dark'), ('light-mode', 'Light Mode'), ('eclipse', 'Eclipse'), ('solarized-light', 'Solarized Light')], default='dracula', max_length=20),
        ),
    ]
