# Generated by Django 5.1.5 on 2025-01-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_idesettings_linting_alter_idesettings_selected_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('new_follower', 'New Follower'), ('new_message', 'New Message'), ('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('task_deleted', 'Task deleted'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_deleted', 'Project Deleted'), ('collaborator_added', 'Collaborator Added')], max_length=20),
        ),
    ]
