# Generated by Django 5.1.5 on 2025-01-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_activitylog_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_storage_limit',
            field=models.PositiveIntegerField(default=10000, help_text='Maximum size of the directory containing all user projects in megabytes (MB).'),
        ),
    ]
